/* English translations. Keys are the exact Chinese strings used on the page. */
window.EN={
"美東七六人追球之旅 Plan A 紐約版 2027.02.25–03.08": "East Coast 76ers Road Trip · Plan A (New York) · 2027.02.25–03.08",
"芝加哥": "Chicago",
"飛機約 2h20": "Flight ~2h20",
"紐約": "New York",
"Amtrak 約 1.5–2h": "Amtrak ~1.5–2h",
"費城": "Philadelphia",
"Amtrak 約 2–3h": "Amtrak ~2–3h",
"華盛頓": "Washington",
"場 NBA 比賽": "NBA games",
"座城市": "cities",
"晚住宿": "nights",
"四場比賽": "4 games",
"週六": "Sat",
"七六人 @ 尼克": "76ers @ Knicks",
"紐約（客場看七六人）": "New York (watch the 76ers on the road)",
"客場": "Away",
"最低約 US$407 起": "From ~US$407",
"TickPick 買票 ↗": "Buy on TickPick ↗",
"週日": "Sun",
"公鹿 @ 尼克": "Bucks @ Knicks",
"紐約（尼克主場）": "New York (Knicks home)",
"尼克主場": "Knicks home",
"最低約 US$214 起": "From ~US$214",
"週三": "Wed",
"黃蜂 @ 七六人": "Hornets @ 76ers",
"費城（主場）": "Philadelphia (home)",
"主場": "Home",
"最低約 US$69 起": "From ~US$69",
"週四": "Thu",
"湖人 @ 七六人": "Lakers @ 76ers",
"全國轉播 Prime Video": "National TV: Prime Video",
"最低約 US$159 起": "From ~US$159",
"去程｜長榮 BR056": "Outbound | EVA Air BR056",
"20:00 桃園起飛 → 19:35 抵達芝加哥歐海爾（同日）": "Departs Taoyuan 20:00 → arrives Chicago O'Hare 19:35 (same day)",
"時間以電子機票為準": "Times follow your e-ticket",
"國內段｜芝加哥 → 紐約（尚未訂）": "Domestic leg | Chicago → New York (not booked yet)",
"例：American 08:15 → 11:29、10:00 → 13:17，直飛約 2 小時 15 分，單程約 NT$3,094 起（Google Flights 2026/10/6 查詢，標示價格偏高）": "e.g. American 08:15 → 11:29, 10:00 → 13:17; nonstop ~2h15; one-way from ~NT$3,094 (Google Flights, 2026/10/6, flagged as high)",
"也有飛 EWR、JFK 的班次；時間為當地時間": "Flights to EWR and JFK also exist; times are local",
"回程｜長榮 BR03": "Return | EVA Air BR03",
"3/6（六）23:55 華盛頓杜勒斯起飛 → 3/8（一）06:05 抵達桃園第二航廈": "Sat 3/6 23:55 departs Washington Dulles → Mon 3/8 06:05 arrives Taoyuan Terminal 2",
"城市間交通（全程不租車）": "Getting between cities (no rental car)",
"2/27 芝加哥 → 紐約": "2/27 Chicago → New York",
"：搭飛機，ORD → LGA 直飛約 2 小時 20 分，時差 +1 小時。LGA 到 LIC 可搭免費 Q70 公車到 Jackson Heights，再換 7 號線到 LIC；有行李或想省時間就叫車。": ": Fly ORD → LGA, nonstop ~2h20, +1 hour time difference. From LGA to LIC, take the free Q70 bus to Jackson Heights, then the 7 train to LIC; take a ride-hail if you have bags or want to save time.",
"3/2 紐約 → 費城": "3/2 New York → Philadelphia",
"：搭 Amtrak，Penn Station 到 30th Street 站，約 1.5–2 小時。票價我沒查，越早買越便宜，出發前再看。": ": Take Amtrak from Penn Station to 30th Street Station, ~1.5–2 hours. I haven't checked fares; the earlier you book, the cheaper — check again before you go.",
"3/5 費城 → 華盛頓": "3/5 Philadelphia → Washington, DC",
"：搭 Amtrak，30th Street 站到 Union Station，Regional 約 2.5–3 小時、Acela 約 2 小時，票價約 US$30–80（依日期浮動）。": ": Take Amtrak from 30th Street Station to Union Station; Regional ~2.5–3 hours, Acela ~2 hours; fares ~US$30–80 (varies by date).",
"全程不租車，避開冬季開車的風險。紐約、費城、華盛頓都用地鐵與叫車，不用停車費。": "No rental car for the whole trip, which avoids winter driving risks. In New York, Philadelphia and Washington we use subways and ride-hail, so no parking fees.",
"2 月底東北部有暴風雪風險，航班與火車都可能延誤，出發前看天氣預報，行程保留彈性。": "Late February can bring snowstorms in the Northeast and both flights and trains may be delayed. Check the forecast before you go and keep the plan flexible.",
"出發前確認": "Before you go",
"ESTA 在出發前 72 小時以前辦好。": "Get your ESTA approved at least 72 hours before departure.",
"四場球票自己買：建議走 NBA 官方認可的票務平台（TickPick、Ticketmaster、SeatGeek 等）。球場禁帶大背包，行李記得先放飯店。": "Buy the four game tickets yourself, preferably on NBA-authorized platforms (TickPick, Ticketmaster, SeatGeek, etc.). Large bags are not allowed in arenas, so leave luggage at the hotel.",
"2/27、2/28 兩場都在 Madison Square Garden，就在 Penn Station 上方，賽日人潮多，提早進場。開賽時間依 TickPick 列表為 2/27 約 8:30 PM、2/28 約 7:30 PM，請再用 NBA 官方賽程確認。": "Both the 2/27 and 2/28 games are at Madison Square Garden, right above Penn Station; game days are crowded, so arrive early. Per TickPick, tip-off is about 8:30 PM on 2/27 and 7:30 PM on 2/28 — please confirm with the official NBA schedule.",
"3/2 搭上午的 Amtrak 去費城，建議提早訂票，下午就能開始逛，3/3 晚上 7:00 才有比賽，不會趕。": "Take a morning Amtrak to Philadelphia on 3/2 and book early. You can start exploring in the afternoon, and the game on 3/3 is at 7:00 PM, so there's no rush.",
"紐約住在 Queens 的 Long Island City（LIC），選 Court Sq 或 Queens Plaza 站走路 10 分鐘內的飯店，搭 E 線到 34 St–Penn Station 看球，賽後也搭 E 線回去。": "In New York we stay in Long Island City (LIC), Queens. Pick a hotel within a 10-minute walk of Court Sq or Queens Plaza station, take the E train to 34 St–Penn Station for the games, and take the E back afterwards.",
"球賽時間以 NBA 官方公佈為準，之後仍可能調整；預訂不可退的機票與住宿前請再確認一次賽程。": "Game times follow the official NBA schedule and may still change; re-check the schedule before booking non-refundable flights or hotels.",
"回程 BR03 是 3/6 23:55 起飛，所以 3/5 要在華盛頓住一晚，3/6 退房後白天逛景點，傍晚前往機場。": "The return flight BR03 departs 23:55 on 3/6, so we stay one night in Washington on 3/5, sightsee after checkout on 3/6 and head to the airport in the evening.",
"長榮華盛頓航線每週只飛四班，改票空間比較小。": "EVA flies the Washington route only four times a week, so there is little room to rebook.",
"想看騎士或 LeBron 博物館的話，看": "If you'd like to see the Cavaliers or the LeBron museum, check out",
"Plan B（開車版）": "Plan B (road trip)",
"。": ".",
"四": "Thu",
"台北出發，抵達芝加哥": "Depart Taipei, arrive in Chicago",
"芝加哥市區（Loop 或 River North）": "Downtown Chicago (Loop or River North)",
"晚": "Evening",
"抵達歐海爾機場": "Arrive at O'Hare Airport",
"入境後搭藍線地鐵進市區約 45 分鐘，或叫車。": "After immigration, take the Blue Line into the city (~45 min) or ride-hail.",
"Check-in 與晚餐": "Check-in and dinner",
"先吃一份芝加哥熱狗，別加番茄醬。早點睡調時差。": "Have a Chicago-style hot dog first — no ketchup. Sleep early to adjust to the time difference.",
"五": "Fri",
"芝加哥一日精華": "Chicago highlights",
"步行＋地鐵": "Walk + subway",
"芝加哥藝術博物館": "Art Institute of Chicago",
"印象派收藏很強，約 2.5 小時。": "Superb Impressionist collection, about 2.5 hours.",
"千禧公園・雲門": "Millennium Park · Cloud Gate",
"午餐後拍鏡面大豆，順著河畔步道走。": "After lunch, photograph \"The Bean\" and stroll along the riverwalk.",
"Magnificent Mile 與 Garrett 爆米花": "Magnificent Mile and Garrett popcorn",
"起司加焦糖的混合口味值得排隊。": "The cheese-and-caramel mix is worth the line.",
"威利斯大樓 Skydeck": "Willis Tower Skydeck",
"挑日落前後上去，提前訂票。": "Go up around sunset and book tickets ahead.",
"深盤披薩": "Deep-dish pizza",
"Lou Malnati's 或 Giordano's，烤製約 45 分鐘，建議先預約。隔天一早飛紐約，今晚別太晚。": "Lou Malnati's or Giordano's; baking takes about 45 minutes, so reserve ahead. We fly to New York early tomorrow, so don't stay out too late.",
"六": "Sat",
"芝加哥 → 紐約｜七六人 @ 尼克": "Chicago → New York | 76ers @ Knicks",
"飛機約 2h20＋公車地鐵": "Flight ~2h20 + bus/subway",
"紐約 Long Island City（Queens）": "Long Island City, New York (Queens)",
"上午": "Morning",
"退房，前往 ORD": "Check out and head to ORD",
"藍線到歐海爾約 45 分鐘，國內線至少提前 1.5–2 小時到。": "The Blue Line to O'Hare takes ~45 min; arrive at least 1.5–2 hours before a domestic flight.",
"ORD → LGA 飛行": "Fly ORD → LGA",
"約 2 小時 17 分，紐約時間 13:17 抵達（時差 +1 小時）。班次例：American 08:15、10:00。": "About 2h17; arrives 13:17 New York time (+1 hour). Example flights: American 08:15, 10:00.",
"入住 LIC 飯店，先放行李": "Check in at the LIC hotel and drop bags",
"LGA 搭免費 Q70 公車到 Jackson Heights，換 7 號線到 LIC；行李多可直接叫車。": "From LGA take the free Q70 bus to Jackson Heights, then the 7 train to LIC; with lots of luggage, just ride-hail.",
"Chelsea Market 與 High Line": "Chelsea Market and the High Line",
"到 MSG 步行約 20–30 分鐘，邊走邊吃。": "About a 20–30 minute walk to MSG; snack as you go.",
"賽前晚餐": "Pre-game dinner",
"Koreatown（32 街）或 Penn Station 周邊，賽日店家會擠。": "Koreatown (32nd St) or around Penn Station; restaurants get crowded on game days.",
"前往 Madison Square Garden": "Head to Madison Square Garden",
"就在 Penn Station 正上方，開賽前 45 分鐘進場。": "Right above Penn Station; get in 45 minutes before tip-off.",
"NBA：七六人 @ 尼克 🏀": "NBA: 76ers @ Knicks 🏀",
"客場看七六人，穿隊服要保持禮貌。": "Watching the 76ers on the road — if you wear a jersey, stay polite.",
"搭 E 線回 LIC": "Take the E train back to LIC",
"在 34 St–Penn Station 上車，E 線深夜也有車，賽後人多，晚上注意安全。": "Board at 34 St–Penn Station. The E runs late at night, but it's crowded after the game, so stay alert at night.",
"日": "Sun",
"紐約｜公鹿 @ 尼克": "New York | Bucks @ Knicks",
"地鐵＋步行": "Subway + walking",
"大都會博物館 The Met": "The Metropolitan Museum of Art (The Met)",
"週日 10:00 開，約 3 小時，先確認當天開放與預約。": "Opens 10:00 on Sundays, about 3 hours; confirm opening and reservations that day.",
"中央公園午餐散步": "Lunch and a walk in Central Park",
"冬天很冷，到 Bethesda Terrace 附近走一小段。": "It's cold in winter; just walk a short stretch near Bethesda Terrace.",
"洛克斐勒中心與 Top of the Rock": "Rockefeller Center and Top of the Rock",
"日落前上去，提前訂時段票。": "Go up before sunset and book a timed ticket.",
"Hell's Kitchen 選擇多，離 MSG 步行可達。": "Plenty of choices in Hell's Kitchen, within walking distance of MSG.",
"開賽前 45 分鐘過安檢。": "Go through security 45 minutes before tip-off.",
"NBA：公鹿 @ 尼克 🏀": "NBA: Bucks @ Knicks 🏀",
"尼克主場，球迷氣氛很強。": "Knicks home game; the crowd energy is intense.",
"在 34 St–Penn Station 上車，賽後人多。": "Board at 34 St–Penn Station; it's crowded after the game.",
"一": "Mon",
"紐約自由日（無球賽）": "Free day in New York (no game)",
"地鐵＋渡輪＋步行": "Subway + ferry + walking",
"自由女神與艾利斯島渡輪": "Statue of Liberty and Ellis Island ferry",
"從 Battery Park 搭船，冬季班次較少，先在官網訂票；天氣差就改去 9/11 紀念館。": "Board at Battery Park; winter sailings are fewer, so book on the official site. If the weather is bad, visit the 9/11 Memorial instead.",
"金融區午餐與華爾街": "Lunch in the Financial District and Wall Street",
"Charging Bull、Oculus 與 9/11 紀念館外觀。": "Charging Bull, the Oculus and the exterior of the 9/11 Memorial.",
"布魯克林大橋步行": "Walk the Brooklyn Bridge",
"走到 DUMBO 拍曼哈頓天際線，風大要保暖。": "Walk to DUMBO for photos of the Manhattan skyline; it's windy, so dress warmly.",
"晚餐": "Dinner",
"Chinatown 或下東城 Katz's Delicatessen。": "Chinatown or Katz's Delicatessen on the Lower East Side.",
"Times Square 夜景": "Times Square at night",
"明天賽前不用早起，可以多逛。": "No early start tomorrow before the game, so you can wander longer.",
"二": "Tue",
"紐約 → 費城": "New York → Philadelphia",
"Amtrak 約 1.5–2h，下午逛景點": "Amtrak ~1.5–2h, sightseeing in the afternoon",
"費城 Center City": "Center City, Philadelphia",
"退房，搭 E 線前往 Penn Station": "Check out and take the E train to Penn Station",
"行李隨身，建議搭上午的車，Amtrak 約 1.5–2 小時；從 LIC 到 Penn Station 要提早出門。": "Keep your luggage with you and take a morning train; Amtrak takes ~1.5–2 hours. Leave early to get from LIC to Penn Station.",
"抵達費城 30th Street 站，入住": "Arrive at 30th Street Station and check in",
"行李先寄放或直接入住。": "Drop your bags or check in right away.",
"雷丁車站市場 Reading Terminal Market": "Reading Terminal Market",
"老字號室內市場，午餐在這裡吃，攤位多半傍晚就收。": "A long-established indoor market — have lunch here; most stalls close by early evening.",
"獨立廳與自由鐘": "Independence Hall and the Liberty Bell",
"冬季獨立廳要事先訂時段票，自由鐘免票。": "In winter, Independence Hall needs timed tickets booked in advance; the Liberty Bell is free.",
"全美最古老的住宅街，十分鐘就能逛完。": "The oldest residential street in the US; ten minutes is enough.",
"City Hall 與 LOVE 公園": "City Hall and LOVE Park",
"市政廳是全美最大的市政建築之一，晚餐在附近吃。": "City Hall is one of the largest municipal buildings in the US; have dinner nearby.",
"三": "Wed",
"費城｜黃蜂 @ 七六人": "Philadelphia | Hornets @ 76ers",
"步行＋地鐵 BSL": "Walk + subway (BSL)",
"費城藝術博物館・洛基階梯": "Philadelphia Museum of Art · Rocky Steps",
"重現跑上階梯拍照。": "Recreate the run up the steps for photos.",
"午餐與自由活動": "Lunch and free time",
"Center City 逛街，或再回雷丁車站市場吃一輪。": "Browse Center City, or head back to Reading Terminal Market for another round of food.",
"吃起司牛肉堡": "Eat a cheesesteak",
"Pat's 與 Geno's 對面開，可兩間都試。": "Pat's and Geno's are across from each other — try both.",
"搭地鐵前往球場": "Take the subway to the arena",
"Broad Street Line 到 NRG 站，球場在南費城運動園區。": "Take the Broad Street Line to NRG station; the arena is in the South Philadelphia sports complex.",
"NBA：黃蜂 @ 七六人 🏀": "NBA: Hornets @ 76ers 🏀",
"Xfinity Mobile Arena，旁邊就是 MLB 費城人球場。": "Xfinity Mobile Arena, right next to the Phillies' MLB ballpark.",
"費城｜湖人 @ 七六人": "Philadelphia | Lakers @ 76ers",
"東州教養所 Eastern State Penitentiary": "Eastern State Penitentiary",
"全美最著名的古蹟監獄，艾爾・卡彭待過，約 2 小時。": "The most famous historic prison in the US, where Al Capone served time; about 2 hours.",
"南街上的馬賽克藝術空間，小而美。": "A mosaic art space on South Street — small but lovely.",
"自由時間": "Free time",
"可去 Citizens Bank Park 外觀與球隊商店，或在 Center City 逛街。": "See the exterior of Citizens Bank Park and the team shop, or browse Center City.",
"出發前往球場": "Head to the arena",
"賽前先在附近吃晚餐。": "Have dinner nearby before the game.",
"NBA：湖人 @ 七六人 🏀": "NBA: Lakers @ 76ers 🏀",
"最後一場，Prime Video 全國轉播，氣氛應該會滿。": "The final game, nationally televised on Prime Video — the atmosphere should be great.",
"費城 → 華盛頓": "Philadelphia → Washington, DC",
"Amtrak 約 2–3h，下午逛景點": "Amtrak ~2–3h, sightseeing in the afternoon",
"華盛頓 Downtown，住 1 晚": "Downtown Washington, 1 night",
"退房，搭 Amtrak 往華盛頓": "Check out and take Amtrak to Washington",
"30th Street 站上車，建議提早訂票，行李可隨身帶。": "Board at 30th Street Station; book early, and luggage can stay with you.",
"抵達 Union Station，入住": "Arrive at Union Station and check in",
"搭 Metro 或步行到飯店，先放行李。": "Take the Metro or walk to the hotel and drop your bags.",
"國家廣場 National Mall": "The National Mall",
"國會山莊、華盛頓紀念碑、林肯紀念堂一路走，約 3 小時。": "Walk from the Capitol to the Washington Monument to the Lincoln Memorial; about 3 hours.",
"白宮外觀與晚餐": "The White House exterior and dinner",
"晚上林肯紀念堂有打燈。": "The Lincoln Memorial is lit up at night.",
"華盛頓一日，夜間 BR03 返台": "A day in Washington, then BR03 home at night",
"白天景點，晚上 Metro 或叫車到 IAD": "Sightseeing by day; Metro or ride-hail to IAD at night",
"退房後行李寄放飯店": "Leave luggage at the hotel after checkout",
"史密森尼博物館": "Smithsonian museums",
"航空太空或自然史擇一，多數免費，部分要預約時段。": "Pick Air and Space or Natural History; most are free, some require timed reservations.",
"喬治城或自由活動": "Georgetown or free time",
"Georgetown 逛街午餐，或再加一間博物館。": "Shop and lunch in Georgetown, or add one more museum.",
"晚餐，取行李": "Dinner, pick up luggage",
"回飯店拿行李。": "Return to the hotel for your bags.",
"前往杜勒斯機場 IAD": "Head to Dulles Airport (IAD)",
"Metro 銀線約 1 小時，深夜班次要先查末班車，不然叫車。": "The Metro Silver Line takes ~1 hour; check the last train for late-night service, or ride-hail.",
"機場報到": "Airport check-in",
"BR03 在 23:55 起飛，國際線至少提前 3 小時。": "BR03 departs at 23:55; arrive at least 3 hours early for international flights.",
"長榮 BR03 起飛": "EVA Air BR03 departs",
"直飛約 15 小時，在機上補眠。": "Nonstop ~15 hours; catch up on sleep on board.",
"抵達桃園": "Arrive in Taoyuan",
"第二航廈，回家。": "Terminal 2 — home.",
"2/25–2/27｜2 晚": "2/25–2/27 | 2 nights",
"選 Loop 或 River North，靠近藍線與紅線地鐵，全程不用租車。": "Choose the Loop or River North, near the Blue and Red Line subways; no rental car needed.",
"2/27–3/2｜3 晚": "2/27–3/2 | 3 nights",
"住 Queens 的 Long Island City，Court Sq 或 Queens Plaza 站附近，E 線到 Penn Station／MSG，先比價。": "Stay in Long Island City, Queens, near Court Sq or Queens Plaza station; the E train goes to Penn Station / MSG. Compare prices first.",
"3/2–3/5｜3 晚": "3/2–3/5 | 3 nights",
"住 Center City，搭 Broad Street Line 去球場最方便。": "Stay in Center City; the Broad Street Line is the easiest way to the arena.",
"3/5–3/6｜1 晚": "3/5–3/6 | 1 night",
"住 Downtown 或靠近 Metro 站，3/6 退房後行李寄放飯店，晚上再去 IAD。": "Stay Downtown or near a Metro station; leave luggage at the hotel after checkout on 3/6 and go to IAD in the evening.",
"約 -6 ~ 2°C，風大且濕冷。": "About -6 to 2°C (21–36°F); windy and damp.",
"約 -3 ~ 6°C，風大。": "About -3 to 6°C (27–43°F); windy.",
"約 -2 ~ 8°C，早晚偏冷。": "About -2 to 8°C (28–46°F); chilly mornings and evenings.",
"約 0 ~ 10°C，白天較溫和。": "About 0 to 10°C (32–50°F); milder in the daytime.",
"🏀 七六人 @ 尼克": "🏀 76ers @ Knicks",
"🏀 公鹿": "🏀 Bucks",
"🏀 黃蜂": "🏀 Hornets",
"🏀 湖人": "🏀 Lakers",
"✈ 飛行中": "✈ In flight",
"✈ 06:05 抵達台北": "✈ 06:05 arrive Taipei",
"台北 → 芝加哥": "Taipei → Chicago",
"約 13.5 小時": "~13.5 hours",
"2/25 長榮 BR056，跨太平洋，過了換日線所以同一天晚上就到。": "2/25 EVA Air BR056 across the Pacific; you cross the date line, so you arrive the same evening.",
"芝加哥 → 紐約": "Chicago → New York",
"約 2 小時 20 分": "~2h20",
"2/27 直飛，約 1,180 公里，比台北飛首爾還短。": "2/27 nonstop, about 1,180 km — shorter than Taipei to Seoul.",
"約 1.5–2 小時": "~1.5–2 hours",
"3/2 Amtrak，約 150 公里。": "3/2 Amtrak, about 150 km.",
"約 2–3 小時": "~2–3 hours",
"3/5 Amtrak，約 225 公里。": "3/5 Amtrak, about 225 km.",
"華盛頓 → 台北": "Washington, DC → Taipei",
"直飛": "Nonstop",
"3/6 長榮 BR003，23:55 起飛，3/8 06:05 抵達桃園。": "3/6 EVA Air BR003 departs 23:55; arrives Taoyuan 06:05 on 3/8.",
"美東七六人追球之旅 Plan B 開車版 2027.02.25–03.08": "East Coast 76ers Road Trip · Plan B (Road trip) · 2027.02.25–03.08",
"開車約 6h（經阿克隆）": "Drive ~6h (via Akron)",
"克里夫蘭": "Cleveland",
"開車約 6.5h": "Drive ~6.5h",
"場七六人比賽": "76ers games",
"三場比賽": "3 games",
"週一": "Mon",
"七六人 @ 騎士": "76ers @ Cavaliers",
"7:00 PM ET｜Rocket Arena": "7:00 PM ET | Rocket Arena",
"克里夫蘭（客場）": "Cleveland (away)",
"全國轉播 NBCSN": "National TV: NBCSN",
"最低約 US$104 起": "From ~US$104",
"城市間交通（開車到費城，之後搭火車）": "Getting between cities (drive to Philadelphia, then train)",
"2/27 芝加哥 → 阿克隆": "2/27 Chicago → Akron",
"：約 350 英里，開車約 5.5–6 小時，時區多 1 小時。阿克隆 → 克里夫蘭再約 45 分鐘。": ": About 350 miles, driving ~5.5–6 hours, with a +1 hour time change. Akron → Cleveland is another ~45 minutes.",
"3/2 克里夫蘭 → 費城": "3/2 Cleveland → Philadelphia",
"：約 430 英里，開車約 6.5–7 小時，走賓州收費公路。": ": About 430 miles, driving ~6.5–7 hours on the Pennsylvania Turnpike.",
"：搭 Amtrak，30th Street 站到 Union Station，Regional 約 2.5–3 小時、Acela 約 2 小時，票價約 US$30–80（依日期浮動），越早買越便宜。": ": Take Amtrak from 30th Street Station to Union Station; Regional ~2.5–3 hours, Acela ~2 hours; fares ~US$30–80 (varies by date), cheaper the earlier you book.",
"一次租車、異地還車：芝加哥取車，3/2 抵達費城後直接還車。異地還車費可能很高，建議多家比價。費城和華盛頓都不租車。": "One rental with a one-way drop-off: pick up in Chicago and return the car on arrival in Philadelphia on 3/2. One-way fees can be high, so compare several companies. No car in Philadelphia or Washington.",
"2 月底東北部有暴風雪風險，出發前看天氣預報，行程有彈性。": "Late February can bring snowstorms in the Northeast; check the forecast before you go and stay flexible.",
"城內不開車：芝加哥、費城、華盛頓用地鐵與叫車，克里夫蘭球賽日步行或叫車。克里夫蘭飯店停車費要先問。": "No driving within cities: use subways in Chicago, Philadelphia and Washington, and walk or ride-hail in Cleveland on game day. Ask about hotel parking fees in Cleveland.",
"城內不開車：芝加哥、費城、華盛頓用地鐵，克里夫蘭球賽日步行或叫車。克里夫蘭飯店停車費要先問。": "No driving within cities: use subways in Chicago, Philadelphia and Washington, and walk or ride-hail in Cleveland on game day. Ask about hotel parking fees in Cleveland.",
"多數高速路段有電子收費，租車公司通常有計費方案，取車時問清楚。": "Most highways use electronic tolls; rental companies usually have a toll plan, so ask when you pick up the car.",
"開車需要有效駕照：台灣駕照加國際駕照最保險，出發前先辦。": "You need a valid driver's license: a Taiwan license plus an International Driving Permit is safest; get it before you go.",
"LeBron 博物館：週六 13:30 左右進場，先在網路上訂票，並確認當天營業時間。近期資料顯示只開週三到週六，所以放在 2/27。": "LeBron museum: enter around 13:30 on Saturday, book tickets online and confirm opening hours. Recent info shows it's open only Wednesday to Saturday, so it's placed on 2/27.",
"三場球票自己買：建議走 NBA 官方認可的票務平台（Ticketmaster、SeatGeek 等）。球場禁帶大背包，行李記得先放飯店。": "Buy the three game tickets yourself, preferably on NBA-authorized platforms (Ticketmaster, SeatGeek, etc.). Large bags are not allowed in arenas, so leave luggage at the hotel.",
"Lou Malnati's 或 Giordano's，烤製約 45 分鐘，建議先預約。隔天要早起開車，今晚別太晚。": "Lou Malnati's or Giordano's; baking takes about 45 minutes, so reserve ahead. We drive early tomorrow, so don't stay out too late.",
"芝加哥 → 阿克隆 LeBron 博物館 → 克里夫蘭": "Chicago → Akron LeBron museum → Cleveland",
"開車約 6h＋45 分鐘（時區多 1 小時）": "Drive ~6h + 45 min (+1 hour time change)",
"克里夫蘭 Downtown": "Downtown Cleveland",
"領車、出發": "Pick up the car and set off",
"走 I-90 轉 Ohio Turnpike，沿路有收費。早上先加滿油。": "Take I-90 onto the Ohio Turnpike; there are tolls along the way. Fill the tank in the morning.",
"中途": "En route",
"午前休息": "Pre-lunch break",
"印第安納與俄亥俄一路平坦，約每 2 小時停一次。": "Indiana and Ohio are flat all the way; stop about every 2 hours.",
"抵達阿克隆，在 House Three Thirty 午餐": "Arrive in Akron; lunch at House Three Thirty",
"館內有餐飲，LeBron 家鄉。": "Food is available inside — LeBron's hometown.",
"LeBron James' Home Court 博物館": "LeBron James' Home Court museum",
"重現童年公寓、高中球館與球鞋收藏，約 1–2 小時。週六營業到 17:00，先在網路上訂票。": "Recreates his childhood apartment, high-school gym and sneaker collection; about 1–2 hours. Open until 17:00 on Saturday — book tickets online.",
"I PROMISE School 外觀": "I PROMISE School exterior",
"就在附近，只能在外面看。": "Right nearby; you can only view it from outside.",
"開車約 45 分鐘到克里夫蘭": "Drive ~45 min to Cleveland",
"入住市區飯店，停車費要先問。": "Check in at a downtown hotel; ask about parking fees first.",
"在 Playhouse Square 或 Ohio City 附近用餐。": "Eat near Playhouse Square or Ohio City.",
"克里夫蘭市區": "Downtown Cleveland",
"步行／叫車": "Walk / ride-hail",
"搖滾名人堂 Rock & Roll Hall of Fame": "Rock & Roll Hall of Fame",
"在伊利湖畔，約 2.5 小時。": "On the shore of Lake Erie; about 2.5 hours.",
"午餐：Ohio City": "Lunch: Ohio City",
"Great Lakes Brewing 是在地經典。": "Great Lakes Brewing is a local classic.",
"克里夫蘭藝術博物館": "Cleveland Museum of Art",
"免費，週日有開，隔天週一休館所以今天去。": "Free and open on Sunday; it's closed Monday, so go today.",
"Public Square 與 Terminal Tower": "Public Square and Terminal Tower",
"看看市區天際線，傍晚光線好。": "Take in the downtown skyline; the evening light is lovely.",
"晚餐與早睡": "Dinner and an early night",
"明天是賽日。": "Tomorrow is game day.",
"克里夫蘭｜七六人 @ 騎士": "Cleveland | 76ers @ Cavaliers",
"步行": "Walking",
"聖誕故事之家（可選）": "A Christmas Story House (optional)",
"電影《聖誕故事》拍攝地，在 Tremont，約 30 分鐘，先查營業時間。": "The filming location of the movie \"A Christmas Story\", in Tremont; about 30 minutes — check opening hours first.",
"午餐": "Lunch",
"可試 West Side Market 周邊，市場營業日要先查。": "Try the area around West Side Market; check the market's opening days first.",
"回飯店休息": "Rest at the hotel",
"整理球衣與外套。": "Get your jersey and jacket ready.",
"到球場周邊覓食": "Find food near the arena",
"Rocket Arena 賽前店家會擠，球場停車費不便宜，建議步行或叫車。": "Places near Rocket Arena get crowded before games and arena parking isn't cheap; walk or ride-hail.",
"進場": "Enter the arena",
"開賽前 45 分鐘抵達，過安檢。": "Arrive 45 minutes before tip-off and go through security.",
"NBA：七六人 @ 騎士 🏀": "NBA: 76ers @ Cavaliers 🏀",
"客場看七六人，穿藍紅色混在騎士球迷裡很有趣。": "Watching the 76ers on the road — wearing blue and red among Cavs fans is fun.",
"克里夫蘭 → 費城": "Cleveland → Philadelphia",
"開車約 6.5–7h": "Drive ~6.5–7h",
"退房出發": "Check out and set off",
"走 I-76 轉 Pennsylvania Turnpike，全程收費。": "Take I-76 onto the Pennsylvania Turnpike; it's tolled all the way.",
"午餐與加油": "Lunch and refuel",
"在 Turnpike 休息站，冬天山區常有雪，出發前看路況。": "At a Turnpike service plaza. The mountains often get snow in winter, so check road conditions before leaving.",
"抵達費城、還車、入住": "Arrive in Philadelphia, return the car, check in",
"先還車再去飯店，之後幾天步行加地鐵 BSL，不用停車。": "Return the car first, then go to the hotel; for the next few days walk and take the BSL subway, so no parking needed.",
"老字號室內市場，攤位多半傍晚就收，建議先吃晚餐。": "A long-established indoor market; most stalls close by early evening, so have dinner first.",
"市政廳是全美最大的市政建築之一。": "City Hall is one of the largest municipal buildings in the US.",
"選 Loop 或 River North，靠近藍線與紅線地鐵，這兩晚不用租車。": "Choose the Loop or River North, near the Blue and Red Line subways; no car needed for these two nights.",
"住 Downtown，離 Rocket Arena 步行可達，問清停車費。": "Stay Downtown, within walking distance of Rocket Arena; ask about parking fees.",
"約 -4 ~ 3°C，湖邊常下雪。": "About -4 to 3°C (25–37°F); often snowy by the lake.",
"🏀 騎士": "🏀 Cavaliers",
"阿克隆": "Akron",
"芝加哥 → 阿克隆 → 克里夫蘭": "Chicago → Akron → Cleveland",
"約 6.5–7 小時": "~6.5–7 hours",
"2/27 租車，約 600 公里，走收費公路，沿路時區多 1 小時。": "2/27 rental car, about 600 km on toll roads, +1 hour time change along the way.",
"3/2 約 690 公里，翻越賓州山區，冬季要看天氣。": "3/2 about 690 km over the Pennsylvania mountains; check the weather in winter.",
"美東七六人追球之旅 Plan C 芝加哥版 2027.02.25–03.08": "East Coast 76ers Road Trip · Plan C (Chicago) · 2027.02.25–03.08",
"飛機約 2h15": "Flight ~2h15",
"籃網 @ 公牛": "Nets @ Bulls",
"7:00 PM ET｜United Center": "7:00 PM ET | United Center",
"芝加哥（公牛主場）": "Chicago (Bulls home)",
"公牛主場": "Bulls home",
"最低約 US$51 起": "From ~US$51",
"國內段｜芝加哥 → 費城（尚未訂）": "Domestic leg | Chicago → Philadelphia (not booked yet)",
"例：Frontier 15:24 → 18:39 約 NT$2,827（基本票價，行李另計）、United 09:06 → 12:19 約 NT$4,047；直飛約 2 小時 15 分": "e.g. Frontier 15:24 → 18:39 ~NT$2,827 (basic fare, bags extra), United 09:06 → 12:19 ~NT$4,047; nonstop ~2h15",
"2/28 同路線 United 約 NT$5,763，Google Flights 2026/10/6 查詢，時間為當地時間": "Same route on 2/28 is ~NT$5,763 on United (Google Flights, 2026/10/6); times are local",
"3/1 芝加哥 → 費城": "3/1 Chicago → Philadelphia",
"：搭飛機，ORD → PHL 直飛約 2 小時 15 分，時差 +1 小時（費城比芝加哥快）。機場線（SEPTA）到 Center City 約 25–30 分鐘。": ": Fly ORD → PHL, nonstop ~2h15, +1 hour (Philadelphia is ahead of Chicago). The SEPTA airport line to Center City takes ~25–30 minutes.",
"也可以改成 2/28 就飛：芝加哥少住一晚、費城多住一晚，2/28 同路線 United 約 NT$5,763（Google Flights 查詢）。": "You can also fly on 2/28: one fewer night in Chicago and one more in Philadelphia; the same route on 2/28 is ~NT$5,763 on United (Google Flights).",
"全程不租車，避開冬季開車的風險。芝加哥、費城、華盛頓都用地鐵與叫車，不用停車費。": "No rental car for the whole trip, which avoids winter driving risks. In Chicago, Philadelphia and Washington we use subways and ride-hail, so no parking fees.",
"三場球票自己買：建議走 NBA 官方認可的票務平台（TickPick、Ticketmaster、SeatGeek 等）。球場禁帶大背包，行李記得先放飯店。": "Buy the three game tickets yourself, preferably on NBA-authorized platforms (TickPick, Ticketmaster, SeatGeek, etc.). Large bags are not allowed in arenas, so leave luggage at the hotel.",
"United Center 在市區西邊，賽後人多，先查好回程的公車、地鐵或叫車。": "United Center is on the west side of the city and gets crowded after games; plan your trip back by bus, train or ride-hail in advance.",
"3/1 飛機兩個班次價差大：Frontier 便宜但行李另計、不含隨身以外，United 貴一些，訂前把行李費加進去一起比較。": "The two flights on 3/1 differ a lot in price: Frontier is cheap but bags cost extra (only a personal item is included), while United costs more. Add bag fees in before comparing.",
"想看紐約或騎士、LeBron 博物館的話，看": "If you'd like to see New York, the Cavaliers or the LeBron museum, check out",
"Plan A（紐約版）": "Plan A (New York)",
"或": "or",
"Lou Malnati's 或 Giordano's，烤製約 45 分鐘，建議先預約。建議先預約。": "Lou Malnati's or Giordano's; baking takes about 45 minutes, so reserve ahead.",
"芝加哥｜籃網 @ 公牛": "Chicago | Nets @ Bulls",
"地鐵＋叫車": "Subway + ride-hail",
"菲爾德自然史博物館或科學與工業博物館": "Field Museum or the Museum of Science and Industry",
"擇一，約 3 小時，冬季人潮較少。": "Pick one; about 3 hours, and winter crowds are smaller.",
"午餐：芝加哥中國城": "Lunch: Chicago Chinatown",
"Chinatown 在南邊，紅線 Cermak–Chinatown 站，吃到熟悉的味道。": "Chinatown is on the south side, at the Red Line Cermak–Chinatown station — a taste of home.",
"芝加哥文化中心與千禧公園": "Chicago Cultural Center and Millennium Park",
"文化中心免費，天花板的蒂芙尼穹頂很漂亮。": "The Cultural Center is free, and its Tiffany dome ceiling is gorgeous.",
"球場在市區西邊，建議在 West Loop 吃。": "The arena is on the west side of the city; eat in the West Loop.",
"前往 United Center": "Head to the United Center",
"在市區西側，搭公車或叫車，賽後人多，先查回程路線。": "On the west side of the city — take a bus or ride-hail; it's crowded after the game, so check the way back first.",
"NBA：籃網 @ 公牛 🏀": "NBA: Nets @ Bulls 🏀",
"公牛主場，全美最知名的球場之一，麥可・喬丹雕像在外面。": "Bulls home game at one of the most famous arenas in the US; the Michael Jordan statue stands outside.",
"芝加哥自由日": "Free day in Chicago",
"林肯公園動物園": "Lincoln Park Zoo",
"免費入場，冬天動物較少，逛一圈約 1.5–2 小時。": "Free admission; fewer animals out in winter; a loop takes about 1.5–2 hours.",
"Lincoln Park 一帶選擇多。": "Plenty of choices around Lincoln Park.",
"芝加哥建築中心與河畔步道": "Chicago Architecture Center and the Riverwalk",
"冬季河上遊船停開，改在室內看建築模型。": "River cruises pause in winter, so see the architecture models indoors instead.",
"360 Chicago 或藍調酒吧": "360 Chicago or a blues club",
"可選觀景台，或晚上去 Kingston Mines 聽藍調。": "Choose the observation deck, or hear blues at Kingston Mines in the evening.",
"明天要搭飛機。": "We fly tomorrow.",
"芝加哥 → 費城（搭飛機）": "Chicago → Philadelphia (by air)",
"ORD → PHL 約 2h15": "ORD → PHL ~2h15",
"退房，逛街買紀念品": "Check out and shop for souvenirs",
"Magnificent Mile 或 Garrett 爆米花，行李先帶著。": "Magnificent Mile or Garrett popcorn; keep your luggage with you.",
"下午": "Afternoon",
"前往 ORD 機場": "Head to ORD airport",
"藍線約 45 分鐘，國內線至少提前 1.5–2 小時到。": "The Blue Line takes ~45 min; arrive at least 1.5–2 hours before a domestic flight.",
"例 15:24": "e.g. 15:24",
"ORD → PHL 飛行": "Fly ORD → PHL",
"直飛約 2 小時 15 分，費城時間 18:39 抵達（芝加哥比費城慢 1 小時）。班次例：Frontier 15:24、United 09:06。": "Nonstop ~2h15; arrives 18:39 Philadelphia time (Chicago is 1 hour behind). Example flights: Frontier 15:24, United 09:06.",
"入住費城 Center City": "Check in at Center City, Philadelphia",
"機場線到市區約 25–30 分鐘。": "The airport line to downtown takes ~25–30 minutes.",
"市政廳附近，雷丁車站市場傍晚就收了。": "Near City Hall; Reading Terminal Market closes by early evening.",
"費城自由日": "Free day in Philadelphia",
"老字號室內市場，午餐在這裡吃。": "A long-established indoor market — have lunch here.",
"Center City 一帶。": "Around Center City.",
"2/25–3/1｜4 晚": "2/25–3/1 | 4 nights",
"3/1–3/5｜4 晚": "3/1–3/5 | 4 nights",
"🏀 公牛": "🏀 Bulls",
"芝加哥 → 費城": "Chicago → Philadelphia",
"約 2 小時 15 分": "~2h15",
"3/1 直飛，約 1,090 公里，比台北飛首爾還短，費城在東岸大西洋邊。": "3/1 nonstop, about 1,090 km — shorter than Taipei to Seoul; Philadelphia is on the Atlantic coast.",
"Plan A｜紐約版": "Plan A | New York",
"芝加哥飛紐約，之後搭 Amtrak，不開車。看 4 場球（紐約 2 場、費城 2 場）。": "Fly Chicago → New York, then take Amtrak; no driving. See 4 games (2 in New York, 2 in Philadelphia).",
"A 紐約": "A New York",
"紐約・不開車": "NYC · No car",
"Plan B｜開車版": "Plan B | Road trip",
"租車芝加哥 → 克里夫蘭 → 費城。含 LeBron 博物館、騎士主場，看 3 場球。冬季長途開車有風險。": "Rent a car: Chicago → Cleveland → Philadelphia. Includes the LeBron museum and a Cavaliers home game; 3 games in total. Long winter drives carry risk.",
"B 開車": "B Road trip",
"開車・克里夫蘭": "Road trip",
"Plan C｜芝加哥版": "Plan C | Chicago",
"待在芝加哥看公牛，3/1 再飛費城，不去紐約、不開車。看 3 場球（公牛 1 場、費城 2 場）。": "Stay in Chicago to watch the Bulls, then fly to Philadelphia on 3/1; no New York, no driving. See 3 games (1 Bulls game, 2 in Philadelphia).",
"C 芝加哥": "C Chicago",
"芝加哥・看公牛": "Chicago",
"總覽": "Overview",
"地圖": "Map",
"月曆": "Calendar",
"行程": "Itinerary",
"住宿交通": "Logistics",
"須知": "Notes",
"機票": "Flights",
"路線地圖｜怎麼飛、怎麼走": "Route map | how we fly and travel",
"行程月曆": "Trip calendar",
"每日行程": "Daily itinerary",
"住宿安排": "Where we stay",
"各城市氣候與穿著": "Weather and what to wear",
"穿著建議": "What to wear",
"羽絨外套、保暖內層、手套與防滑鞋。": "Down jacket, warm base layers, gloves and non-slip shoes.",
"賽日": "Game day",
"賽": "Game",
"前一天": "Previous day",
"後一天": "Next day",
"天行程": "days",
"共有 3 個版本，點最上方切換。": "There are 3 versions — switch at the very top.",
"週二": "Tue",
"週五": "Fri",
"空中": "In the air",
"台北": "Taipei",
"需請假": "Leave needed",
"（半天?）": "(half day?)",
"台灣放假日": "Taiwan public holiday",
"球賽": "Game",
"航班": "Flight",
"點日期可看當天行程": "Tap a date to see that day",
"飛機": "Flight",
"火車": "Train",
"開車": "Drive",
"互動地圖": "Interactive map",
"示意圖": "Diagram",
"電腦：拖曳移動，點一下地圖後用滾輪縮放；手機：用兩指縮放、移動地圖。點城市圖釘可看日期。": "Desktop: drag to pan, click the map first and then use the scroll wheel to zoom. Phone: pinch with two fingers to zoom and pan. Tap a city pin for its dates.",
"美國很大，城市之間常要搭飛機：芝加哥在中西部（五大湖旁），費城、紐約、華盛頓都在東北岸，彼此很近、火車就夠。地圖只是示意，距離為約略值。": "The US is big, so you often fly between cities: Chicago is in the Midwest (by the Great Lakes), while Philadelphia, New York and Washington are all on the Northeast coast, close together — trains are enough. The map is only a diagram and distances are approximate.",
"賽程資料來源：NBA 官方與 ESPN 公佈之 2026-27 例行賽賽程。景點開放時間與票務請出發前再確認。": "Schedule source: NBA and ESPN 2026–27 regular-season schedules. Please re-check attraction hours and ticketing before you go.",
"美東七六人追球之旅": "East Coast 76ers Road Trip",
"五大湖": "Great Lakes",
"大西洋": "Atlantic Ocean",
"台灣": "Taiwan",
"美國": "USA",
"左下小圖：世界位置。紅框＝本圖範圍，虛線＝台北來回的長程航班": "Inset: world location. Red box = this map's area; dashed lines = long-haul flights to and from Taipei",
"回到行程": "Trip view",
"全球視角": "Global view",
"樣式：簡約": "Style: Minimal",
"樣式：彩色": "Style: Color",
"票價為 TickPick 2026/10/6 查到的單張最低起價（含費用），會隨時間浮動。": "Prices are the lowest single-ticket asking prices found on TickPick on 2026/10/6 (fees included) and may change over time.",
"和平紀念日": "Peace Memorial Day",
"和平紀念日補假": "Peace Memorial Day (observed)",
"8:30 PM ET｜Madison Square Garden": "8:30 PM ET | Madison Square Garden",
"7:30 PM ET｜Madison Square Garden": "7:30 PM ET | Madison Square Garden",
"7:00 PM ET｜Xfinity Mobile Arena": "7:00 PM ET | Xfinity Mobile Arena",
"語言": "Language",
"外觀": "Appearance",
"自動": "Auto",
"淺色": "Light",
"深色": "Dark",
"長程機票選項（參考）": "Long-haul ticket options (for reference)",
"目前計畫": "Current plan",
"較便宜": "Cheaper",
"長榮直飛": "EVA Air nonstop",
"BR056 去程・BR03 回程": "BR056 outbound · BR03 return",
"聯合航空（經舊金山轉機）": "United Airlines (via San Francisco)",
"去程進芝加哥歐海爾，回程從華盛頓雷根國家機場出發": "Fly into Chicago O'Hare, return from Washington Reagan National",
"去程": "Outbound",
"回程": "Return",
"2/25（四）20:00 桃園 → 19:35 芝加哥歐海爾（同日）": "Thu 2/25 20:00 Taoyuan → 19:35 Chicago O'Hare (same day)",
"直飛 13 小時 35 分": "Nonstop, 13h35",
"3/6（六）23:55 華盛頓杜勒斯 → 3/8（一）06:05 桃園": "Sat 3/6 23:55 Washington Dulles → Mon 3/8 06:05 Taoyuan",
"直飛 17 小時 10 分": "Nonstop, 17h10",
"約 NT$51,370": "~NT$51,370",
"經濟艙・1 位成人・來回含稅": "Economy · 1 adult · round trip incl. taxes",
"2/25（四）23:20 桃園 → 2/26（五）05:04 芝加哥歐海爾": "Thu 2/25 23:20 Taoyuan → Fri 2/26 05:04 Chicago O'Hare",
"轉機 1 次（舊金山 3 小時 45 分），共 19 小時 44 分": "1 stop (San Francisco, 3h45), 19h44 total",
"3/6（六）18:00 華盛頓雷根國家機場 → 3/8（一）05:45 桃園": "Sat 3/6 18:00 Washington Reagan National → Mon 3/8 05:45 Taoyuan",
"轉機 1 次（舊金山 1 小時 48 分），共 22 小時 45 分": "1 stop (San Francisco, 1h48), 22h45 total",
"基本經濟艙": "Basic Economy",
"第 1 件託運行李免費；選位另收費；不可退款、不可升等": "First checked bag free; seat selection costs extra; non-refundable, no upgrades",
"經濟艙（可部分退款）": "Economy (partially refundable)",
"可免費選位，可託運 2 件行李；可部分退款，改票收手續費": "Free seat selection and 2 checked bags; partial refund allowed, change fee applies",
"經濟艙": "Economy",
"可免費選位，可託運 2 件行李；不可退款": "Free seat selection and 2 checked bags; non-refundable",
"比長榮便宜約 NT$18,798，但總飛行時間較長。抵達芝加哥是 2/26 清晨，2/25 晚上的行程會往後移；回程 18:00 起飛，3/6 在華盛頓的時間比較少。": "About NT$18,798 cheaper than EVA, but total travel time is longer. You land in Chicago early on 2/26, so the evening plans on 2/25 shift back; the return flight leaves at 18:00, so there is less time in Washington on 3/6.",
"在 Google Flights 查看 ↗": "View on Google Flights ↗",
"價格為 Google Flights 2026/10/6 查到的 1 位成人來回總價（含稅），會隨時間浮動，以實際訂票頁為準。連結會開啟該航班組合的搜尋結果。": "Prices are the round-trip totals for 1 adult (taxes included) found on Google Flights on 2026/10/6 and may change; the booking page is authoritative. Each link opens the search results for that flight combination.",
"· 賽": "· Game",
"住宿：": "Stay: "
};
